/* ভুবনডাঙ্গার কবিতা — common shell/controller v1 */
(function(W,D){'use strict';
const $=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>[...r.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch(e){return f}},esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const NAV=[['index.html','⌂','হোম'],['poem.html','🖋','কবিতা'],['recitation.html','🎙','আবৃত্তি'],['madhyorater-prolap.html','☾','মধ্যরাতের প্রলাপ'],['environment.html','🌱','পরিবেশের কথা'],['letter.html','✉','চিঠিপত্র'],['small-prolap.html','☁','ছোট কথার প্রলাপ'],['discussion.html','◌','সাহিত্য আলোচনা'],['famous-poet.html','♙','খ্যাতিমান কবি'],['famous-quotes.html','❝','মনীষীদের বাণী'],['humanitarian-notice.html','♡','মানবিক আবেদন']];
const THEMES=[['pearl','মুক্তা গ্লাস'],['moon','নীল জ্যোৎস্না'],['lavender','ল্যাভেন্ডার'],['rose','অরোরা গোলাপি']];
const file=()=>location.pathname.split('/').pop().toLowerCase()||'index.html';
let user=read('bhubondangaCurrentUser',null);
function nav(){return '<nav class="bd-core-nav">'+NAV.map(([h,i,t])=>`<a href="${h}" ${file()===h?'aria-current="page"':''}><span class="bd-core-icon">${i}</span><span>${t}</span><span>›</span></a>`).join('')+'</nav>';}
function identity(){return '<section class="bd-core-card bd-core-identity"><div class="bd-core-logo">🌿</div><h2><a href="index.html">আপন ভুবন</a></h2><p>আপনার লেখা, পাঠ ও সাহিত্যিক পথচলার নিজস্ব জায়গা।</p><div class="bd-core-quote">“আপনার ক্ষতগুলোকে জ্ঞানে পরিণত করুন।”</div></section>';}
function themes(){const g=localStorage.getItem('bhubondangaGlassTheme')||'pearl',m=localStorage.getItem('bhubondangaThemeMode')||'light';return `<section class="bd-core-card bd-core-theme"><div class="bd-core-title"><h3>চারটি থিম</h3><small>সরাসরি পরিবর্তন</small></div><div class="bd-core-theme-grid">${THEMES.map(([k,t])=>`<button type="button" class="bd-core-theme-button" data-bd-glass-choice="${k}" aria-pressed="${g===k}"><span class="bd-core-swatch"></span>${t}</button>`).join('')}</div><button type="button" class="bd-core-mode" data-bd-mode><span class="bd-core-icon">◐</span><span>আলো: <b data-bd-mode-label>${m==='dark'?'ডার্ক':m==='middle'?'মিডল':'লাইট'}</b></span><span>›</span></button></section>`;}
function account(){if(!user)return '<section class="bd-core-card bd-core-account"><div class="bd-core-avatar">♙</div><strong>অতিথি পাঠক</strong><p>লেখা প্রকাশ ও প্রতিক্রিয়ার জন্য লগইন করুন</p><div class="bd-core-account-actions"><a class="primary" href="login.html">লগইন</a><a href="register.html">রেজিস্টার</a></div></section>';const role=String(user.role||'user').toLowerCase(),name=user.name||user.displayName||user.username||user.email||'ভুবনডাঙ্গার সদস্য',avatar=user.avatar||user.avatar_url||user.profileImage||'',profile=role==='founder'?'founder-profile.html':role==='admin'?'admin-profile.html':'profile.html',dash=role==='founder'?'founder-dashboard.html':role==='admin'?'admin-dashboard.html':'';return `<section class="bd-core-card bd-core-account"><div class="bd-core-avatar">${avatar?`<img src="${esc(avatar)}" alt="">`:'♙'}</div><strong>${esc(name)}</strong><p>আপনার ব্যক্তিগত ভুবন</p><div class="bd-core-account-actions"><a class="primary" href="${profile}">প্রোফাইল</a><a href="edit-profile.html">সম্পাদনা</a><a href="messages.html">ইনবক্স</a><a href="notifications.html">নোটিফিকেশন</a>${dash?`<a class="wide" href="${dash}">ড্যাশবোর্ড</a>`:''}<button class="wide" type="button" data-bd-logout>লগআউট</button></div></section>`;}
function quick(){const a=[['bhubondangar-lekhok.html','ভুবনডাঙ্গার লেখক'],['favorite-authors.html','প্রিয় লেখক'],['messages.html','ইনবক্স'],['notifications.html','নোটিফিকেশন'],['archive.html','আর্কাইভ'],['memories.html','মেমোরিজ'],['settings.html','সেটিংস'],['about.html','আমাদের সম্পর্কে'],['contact.html','যোগাযোগ'],['complaint.html','অভিযোগ'],['policy.html','নীতিমালা']];return '<section class="bd-core-card bd-core-quick"><div class="bd-core-title"><h3>দ্রুত দেখুন</h3></div><nav class="bd-core-nav">'+a.map(([h,t])=>`<a href="${h}"><span class="bd-core-icon">•</span><span>${t}</span><span>›</span></a>`).join('')+'</nav></section>';}
function leftHTML(){return identity()+'<section class="bd-core-card bd-core-nav-card">'+nav()+'</section>'+themes()+'<section class="bd-core-card bd-core-contact"><a href="founder-profile.html">জরুরি প্রয়োজনে মাহমুদ সোহেলের সঙ্গে যোগাযোগ করুন</a></section>';}
function rightHTML(){return account()+quick()+themes();}
function findShell(){const left=$('#leftSidebar')||$('.left-sidebar'),right=$('#rightSidebar')||$('.right-sidebar'),ld=$('#mobileDrawer')||$('#leftDrawer'),rd=$('#rightMobileDrawer')||$('#rightDrawer')||$('#midnightRightDrawer');return{left,right,ld,rd};}
function fallback(side){const a=D.createElement('aside');a.className=`bd-fallback-rail bd-fallback-${side}`;a.id='bdFallback'+(side==='left'?'Left':'Right');D.body.appendChild(a);D.body.classList.add('bd-global-rails');return a;}
function drawer(side){const a=D.createElement('aside');a.className=`bd-core-drawer bd-core-drawer-${side}`;a.id='bdCoreDrawer'+(side==='left'?'Left':'Right');D.body.appendChild(a);return a;}
function header(title){return `<div class="bd-core-drawer-head"><strong>${title}</strong><button type="button" class="bd-core-close" data-bd-close>×</button></div>`;}
function render(){let{left,right,ld,rd}=findShell();if(!left)left=fallback('left');if(!right)right=fallback('right');if(!ld)ld=drawer('left');else ld.classList.add('bd-core-drawer','bd-core-drawer-left');if(!rd)rd=drawer('right');else rd.classList.add('bd-core-drawer','bd-core-drawer-right');left.innerHTML=leftHTML();right.innerHTML=rightHTML();ld.innerHTML=header('🌿 আপন ভুবন')+leftHTML();rd.innerHTML=header(user?'আপনার ভুবন':'অতিথি পাঠক')+rightHTML();ensureControls();syncTheme();}
function ensureControls(){const old=$$('.edge-menu,.edge,.midnight-edge').filter(x=>!x.classList.contains('bd-core-edge'));old.forEach(x=>x.hidden=true);let l=$('#bdCoreEdgeLeft'),r=$('#bdCoreEdgeRight'),b=$('#bdCoreBackdrop');if(!l){l=D.createElement('button');l.id='bdCoreEdgeLeft';l.className='bd-core-edge bd-core-edge-left';l.type='button';l.textContent='›';l.setAttribute('aria-label','বাম সাইডবার খুলুন');D.body.appendChild(l);}if(!r){r=D.createElement('button');r.id='bdCoreEdgeRight';r.className='bd-core-edge bd-core-edge-right';r.type='button';r.textContent='‹';r.setAttribute('aria-label','ডান সাইডবার খুলুন');D.body.appendChild(r);}if(!b){b=D.createElement('div');b.id='bdCoreBackdrop';b.className='bd-core-backdrop';D.body.appendChild(b);}l.onclick=()=>open('left');r.onclick=()=>open('right');b.onclick=close;}
function open(side){close();const d=$(side==='left'?'#bdCoreDrawerLeft,.bd-core-drawer-left':'#bdCoreDrawerRight,.bd-core-drawer-right');if(d){d.classList.add('open');$('#bdCoreBackdrop').classList.add('show');D.body.classList.add('bd-core-drawer-open');}}
function close(){$$('.bd-core-drawer').forEach(x=>x.classList.remove('open'));$('#bdCoreBackdrop')?.classList.remove('show');D.body.classList.remove('bd-core-drawer-open','locked','drawer-open','theme-open','unified-theme-open');}
function setGlass(v){D.documentElement.dataset.bdGlass=v;localStorage.setItem('bhubondangaGlassTheme',v);localStorage.setItem('bhubondangaStyle',v);syncTheme();}
function setMode(v){D.documentElement.dataset.bdTheme=v;D.documentElement.dataset.theme=v;D.documentElement.dataset.mode=v;localStorage.setItem('bhubondangaThemeMode',v);localStorage.setItem('bhubondangaTheme',v);syncTheme();}
function syncTheme(){const g=D.documentElement.dataset.bdGlass||'pearl',m=D.documentElement.dataset.bdTheme||'light';$$('[data-bd-glass-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.bdGlassChoice===g)));$$('[data-bd-mode-label]').forEach(x=>x.textContent=m==='dark'?'ডার্ক':m==='middle'?'মিডল':'লাইট');}
async function logout(){try{await W.BhubondangaAuth?.signOut?.()}catch(e){}localStorage.removeItem('bhubondangaCurrentUser');location.href='login.html';}
async function refreshUser(){try{const info=await W.BhubondangaAuth?.current?.();if(info?.legacyUser){user=info.legacyUser;render();}}catch(e){}}
function offline(){let x=$('#bdOffline');if(navigator.onLine){x?.remove();return;}if(!x){x=D.createElement('div');x.id='bdOffline';x.className='bd-offline-badge';x.textContent='ইন্টারনেট সংযোগ নেই—কিছু তথ্য আপডেট নাও হতে পারে';D.body.appendChild(x);}}
function init(){setGlass(localStorage.getItem('bhubondangaGlassTheme')||localStorage.getItem('bhubondangaStyle')||'pearl');setMode(localStorage.getItem('bhubondangaThemeMode')||localStorage.getItem('bhubondangaTheme')||D.documentElement.dataset.theme||'light');W.BhubondangaCalendar?.update?.();render();refreshUser();W.BhubondangaProfanity?.attach?.();offline();setInterval(()=>W.BhubondangaCalendar?.update?.(),60000);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});}
D.addEventListener('click',e=>{const c=e.target.closest('[data-bd-close]');if(c){close();return}const g=e.target.closest('[data-bd-glass-choice]');if(g){setGlass(g.dataset.bdGlassChoice);return}const m=e.target.closest('[data-bd-mode]');if(m){const cur=D.documentElement.dataset.bdTheme||'light',a=['light','middle','dark'];setMode(a[(a.indexOf(cur)+1)%a.length]);return}if(e.target.closest('[data-bd-logout]'))logout();});D.addEventListener('keydown',e=>{if(e.key==='Escape')close();});W.addEventListener('online',offline);W.addEventListener('offline',offline);if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window,document);