/* ভুবনডাঙ্গা messages safety/realtime helpers v1 */
(function(W){'use strict';
const api={};const client=()=>W.BhubondangaData?.client?.();const current=()=>W.BhubondangaData?.user?.();
api.markSeen=async conversationId=>{const c=client(),u=await current();if(!c||!u||!conversationId)return;await c.from('conversation_members').update({last_read_at:new Date().toISOString()}).eq('conversation_id',conversationId).eq('user_id',u.id);};
api.unsendForEveryone=async messageId=>{const c=client(),u=await current();if(!c||!u)throw new Error('লগইন প্রয়োজন');const{error}=await c.from('messages').update({unsent_for_everyone:true,body:'',attachment_url:'',attachment_name:'',attachment_type:'',edited_at:new Date().toISOString()}).eq('id',messageId).eq('sender_id',u.id);if(error)throw error;};
api.removeForMe=async messageId=>{const c=client(),u=await current();if(!c||!u)throw new Error('লগইন প্রয়োজন');const{error}=await c.from('message_hidden_for_user').upsert({message_id:messageId,user_id:u.id});if(error)throw error;};
api.report=async({messageId,reason='other',priority='normal',details=''})=>{const c=client(),u=await current();if(!c||!u)throw new Error('লগইন প্রয়োজন');const{error}=await c.from('reports').insert({reporter_id:u.id,target_type:'message',target_id:String(messageId),reason,priority,details});if(error)throw error;};
function ping(){const pref=JSON.parse(localStorage.getItem('bhubondangaMessagePreferences')||'{}');if(pref.vibration!==false&&navigator.vibrate)navigator.vibrate([90,50,90]);if(pref.sound===false)return;try{const A=W.AudioContext||W.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=720;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.08,a.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.18);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.2);}catch(e){}}
function scrollOld(){const box=document.querySelector('[data-message-scroll],.messages-scroll,.message-list,.chat-messages');if(!box)return;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight;});}
function init(){scrollOld();document.addEventListener('click',async e=>{const b=e.target.closest('[data-message-action]');if(!b)return;const id=b.dataset.messageId;try{if(b.dataset.messageAction==='unsend-everyone')await api.unsendForEveryone(id);if(b.dataset.messageAction==='remove-me')await api.removeForMe(id);}catch(err){console.warn(err);}});const cid=document.body.dataset.conversationId;if(cid){api.markSeen(cid).catch(()=>{});const c=client();if(c)c.channel('messages:'+cid).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+cid},payload=>{ping();scrollOld();document.dispatchEvent(new CustomEvent('bhubondanga:new-message',{detail:payload.new}));}).subscribe();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();W.BhubondangaMessages=Object.freeze({...api,ping});
})(window);