(()=>{'use strict';
if(window.BD_SIGNAL_CENTER)return;
const W=window,D=document,LS=localStorage;
const URL=W.BD_SUPABASE_URL||'https://ihjiisysrwgxxkuywuhc.supabase.co';
const KEY=W.BD_SUPABASE_KEY||'sb_publishable_2ofR9FO078M1Eu-m0Q8FLg_WqN6iIxz';
const S={client:null,session:null,uid:'',notif:0,msg:0,audio:null,primed:false,pending:'',channels:[],seen:new Set(),timer:null,ready:false};
const q=(s,c=D)=>c.querySelector(s),qa=(s,c=D)=>[...c.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const path=()=>location.pathname.split('/').pop().toLowerCase();
function bn(n){return String(Math.max(0,Number(n)||0)).replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d])}
function get(k,f=''){try{const v=LS.getItem(k);return v==null?f:v}catch{return f}}
function set(k,v){try{LS.setItem(k,String(v))}catch{}}
function json(k,f=[]){try{const v=JSON.parse(get(k,''));return v??f}catch{return f}}
function css(){if(q('#bd-live-signals-css'))return;const s=D.createElement('style');s.id='bd-live-signals-css';s.textContent=`
[data-bd-signal-link]{position:relative!important}.bd-signal-badge{position:absolute;z-index:25;right:-5px;top:-6px;min-width:18px;height:18px;padding:0 5px;border-radius:999px;display:grid;place-items:center;background:#e5394f;color:white;border:2px solid var(--bd-card2,#fff);font:800 9px/1 system-ui,-apple-system,sans-serif;box-shadow:0 4px 10px rgba(174,35,58,.22);transform-origin:center}.bd-signal-badge[hidden]{display:none!important}.bd-signal-badge.pulse{animation:bdSignalPulse .55s ease}.bd-signal-dot{position:absolute;right:1px;top:1px;width:8px;height:8px;border-radius:50%;background:#e5394f;box-shadow:0 0 0 3px rgba(229,57,79,.14)}@keyframes bdSignalPulse{0%{transform:scale(.7)}45%{transform:scale(1.28)}100%{transform:scale(1)}}
.bd-user-actions [data-bd-signal-link]{overflow:visible!important}.bd-user-actions .bd-signal-badge{right:5px;top:4px}.bd-side-row[data-bd-signal-link] .bd-signal-badge{right:5px;top:5px}.bd-head-actions [data-bd-signal-link] .bd-signal-badge{right:-4px;top:-5px}
`;D.head.appendChild(s)}
function client(){if(S.client)return S.client;S.client=W.BD_SUPABASE||W.supabaseClient||W.BhubondangaAuth?.client||null;if(!S.client&&W.supabase?.createClient){try{S.client=W.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});W.BD_SUPABASE=W.BD_SUPABASE||S.client;W.supabaseClient=W.supabaseClient||S.client}catch(_){}}return S.client}
async function auth(){const c=client();if(!c)return null;try{if(W.BhubondangaAuth?.session){const s=await W.BhubondangaAuth.session();if(s)return s}const r=await c.auth.getSession();return r.data?.session||null}catch{return null}}
function stamp(kind){return `bd-signal-${kind}-seen:${S.uid||'guest'}`}
function seenTime(kind){const v=get(stamp(kind),'');const d=Date.parse(v);return Number.isFinite(d)?d:Date.now()-7*864e5}
function setSeenTime(kind,t=Date.now()){set(stamp(kind),new Date(t).toISOString())}
function badgeFor(a,kind){let b=a.querySelector(`.bd-signal-badge[data-kind="${kind}"]`);if(!b){b=D.createElement('span');b.className='bd-signal-badge';b.dataset.kind=kind;b.hidden=true;a.appendChild(b)}return b}
function injectBadges(){css();const pairs=[['notification','notifications.html'],['message','messages.html']];for(const [kind,file] of pairs){qa(`a[href*="${file}"]`).forEach(a=>{a.dataset.bdSignalLink='1';const b=badgeFor(a,kind);const n=kind==='notification'?S.notif:S.msg;b.textContent=n>99?'99+':bn(n);b.hidden=!n})}}
function pulse(kind){injectBadges();qa(`.bd-signal-badge[data-kind="${kind}"]`).forEach(b=>{b.classList.remove('pulse');void b.offsetWidth;b.classList.add('pulse')})}
function setCount(kind,n,doPulse=false){n=Math.max(0,Number(n)||0);if(kind==='notification')S.notif=n;else S.msg=n;set(`bd-signal-count-${kind}:${S.uid||'guest'}`,n);injectBadges();if(doPulse&&n)pulse(kind);W.dispatchEvent(new CustomEvent('bd:signal-count',{detail:{kind,count:n}}))}
function prime(){if(S.primed)return;S.primed=true;try{const AC=W.AudioContext||W.webkitAudioContext;if(AC){S.audio=S.audio||new AC();S.audio.resume?.()}}catch(_){}if(S.pending){const k=S.pending;S.pending='';setTimeout(()=>sound(k),40)}}
function tone(freq,dur=.11,vol=.035,delay=0){try{const AC=W.AudioContext||W.webkitAudioContext;if(!AC)return;const a=S.audio||(S.audio=new AC());if(a.state==='suspended')a.resume?.();const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,a.currentTime+delay);g.gain.exponentialRampToValueAtTime(vol,a.currentTime+delay+.018);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+dur);o.connect(g);g.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+dur+.03)}catch(_){}}
function sound(kind){if(!S.primed){S.pending=kind;return}if(kind==='message'){tone(690,.105,.042,0);tone(980,.09,.03,.13)}else{tone(820,.09,.034,0);tone(1100,.08,.026,.11)}try{navigator.vibrate?.(kind==='message'?[90,55,110]:[70,45,70])}catch(_){}}
function systemNotify(title,body,tag){try{if(D.hidden&&'Notification'in W&&Notification.permission==='granted'){const n=new Notification(title||'ভুবনডাঙ্গার কবিতা',{body:body||'নতুন আপডেট এসেছে',tag:tag||'bd-signal'});n.onclick=()=>{W.focus();n.close()}}}catch(_){}}
function seenEvent(id){id=String(id||'');if(!id)return false;if(S.seen.has(id))return true;const arr=json('bd-signal-seen-events',[]);if(arr.includes(id)){S.seen.add(id);return true}S.seen.add(id);arr.unshift(id);try{LS.setItem('bd-signal-seen-events',JSON.stringify([...new Set(arr)].slice(0,240)))}catch(_){}return false}
function recipient(row){return String(row?.recipient_id||row?.user_id||row?.to_user_id||row?.target_user_id||'')}
function belongs(row){const r=recipient(row);return !r||!S.uid||r===String(S.uid)}
function isRead(row,last){if(row?.read===true||row?.is_read===true||row?.read_at||row?.seen_at)return true;if(row?.read===false||row?.is_read===false)return false;const t=Date.parse(row?.created_at||row?.createdAt||0);return Number.isFinite(t)?t<=last:false}
function normLocalNotification(x){return {...x,id:x.id||x.notification_id||('local-'+String(x.createdAt||x.created_at||Math.random())),created_at:x.created_at||x.createdAt||new Date().toISOString(),title:x.title||x.message||'নোটিফিকেশন',message:x.message||x.body||''}}
async function getNotificationRows(){const rows=[];for(const x of json('bhubondangaNotifications',[])){const n=normLocalNotification(x);if(belongs(n))rows.push({...n,_local:true})}const c=client();if(c&&S.uid){let r=null;try{r=await c.from('notifications').select('*').order('created_at',{ascending:false}).limit(250)}catch(_){}if(r?.error){try{r=await c.from('notifications').select('*').limit(250)}catch(_){}}if(!r?.error&&Array.isArray(r?.data))for(const x of r.data)if(belongs(x))rows.push(x)}const m=new Map();for(const x of rows){const k=String(x.id||x.notification_id||[x.type,x.created_at,x.title,x.message].join('|'));if(!m.has(k))m.set(k,x)}return [...m.values()].sort((a,b)=>Date.parse(b.created_at||b.createdAt||0)-Date.parse(a.created_at||a.createdAt||0))}
function validMessage(row){if(!row||String(row.sender_id||'')===String(S.uid||''))return false;const type=String(row.message_type||'').toLowerCase(),body=String(row.body||'');if(type==='reaction'||type.startsWith('call_')||body.startsWith('__BDRTC__'))return false;return true}
async function getUnreadMessages(){if(!S.uid)return 0;const c=client(),last=seenTime('message'),iso=new Date(last).toISOString();if(!c)return Number(get(`bd-signal-count-message:${S.uid}`,0))||0;let r=null;try{r=await c.from('messages').select('id,conversation_id,sender_id,body,message_type,created_at').gt('created_at',iso).order('created_at',{ascending:false}).limit(500)}catch(_){}if(r?.error){try{r=await c.from('messages').select('*').gt('created_at',iso).limit(500)}catch(_){}}if(r?.error||!Array.isArray(r?.data))return Number(get(`bd-signal-count-message:${S.uid}`,0))||0;return r.data.filter(validMessage).length}
async function refresh(){if(!S.uid)return;try{const rows=await getNotificationRows(),last=seenTime('notification');setCount('notification',rows.filter(x=>!isRead(x,last)).length)}catch(_){}try{setCount('message',await getUnreadMessages())}catch(_){}}
async function markNotificationsRead(){if(!S.uid)return;setSeenTime('notification');try{let a=json('bhubondangaNotifications',[]);a=a.map(x=>belongs(x)?{...x,read:true,read_at:new Date().toISOString()}:x);LS.setItem('bhubondangaNotifications',JSON.stringify(a))}catch(_){}const c=client();if(c){const now=new Date().toISOString(),variants=[['recipient_id',{read:true,read_at:now}],['user_id',{read:true,read_at:now}],['recipient_id',{is_read:true}],['user_id',{is_read:true}]];for(const [col,payload] of variants){try{const r=await c.from('notifications').update(payload).eq(col,S.uid);if(!r.error)break}catch(_){} }}setCount('notification',0);return true}
async function markMessagesRead(){if(!S.uid)return;const now=Date.now();setSeenTime('message',now);setCount('message',0);const c=client();const cid=W.__BD_MESSENGER_STATE?.cid;if(c&&cid){for(const payload of [{last_read_at:new Date(now).toISOString()},{last_seen_at:new Date(now).toISOString()}]){try{const r=await c.from('conversation_members').update(payload).eq('conversation_id',cid).eq('user_id',S.uid);if(!r.error)break}catch(_){} }}return true}
function titleBody(row,kind){if(kind==='message')return ['নতুন বার্তা',row?.body&&!String(row.body).startsWith('__BDRTC__')?String(row.body).slice(0,120):'আপনার কাছে নতুন বার্তা এসেছে'];return [row?.title||'নতুন নোটিফিকেশন',row?.message||row?.body||'ভুবনডাঙ্গায় নতুন আপডেট এসেছে']}
function handleIncomingNotification(row){if(!S.uid||!belongs(row))return;if(seenEvent('n:'+String(row.id||row.created_at||Math.random())))return;setCount('notification',S.notif+1,true);sound('notification');const [t,b]=titleBody(row,'notification');systemNotify(t,b,'bd-notification')}
function handleIncomingMessage(row,opt={}){if(!S.uid||!validMessage(row))return;const id='m:'+String(row.id||row.created_at||Math.random());if(seenEvent(id))return;const messenger=path()==='messages.html',same=messenger&&String(W.__BD_MESSENGER_STATE?.cid||'')===String(row.conversation_id||'')&&!D.hidden;if(same){markMessagesRead();return}setCount('message',S.msg+1,true);sound('message');const [t,b]=titleBody(row,'message');systemNotify(opt.name||t,b,'bd-message')}
async function sendNotification(o={}){const recipientId=String(o.recipientId||o.recipient_id||'');if(!recipientId)return false;const ss=S.session||await auth(),actor=String(o.actorId||ss?.user?.id||''),md=ss?.user?.user_metadata||{},actorName=o.actorName||md.full_name||md.name||ss?.user?.email?.split('@')[0]||'একজন সদস্য',now=new Date().toISOString();const base={recipient_id:recipientId,actor_id:actor,type:o.type||'general',title:o.title||'নতুন নোটিফিকেশন',message:o.message||'',url:o.url||'',post_id:o.postId||o.post_id||null,created_at:now,read:false};try{const a=json('bhubondangaNotifications',[]);a.unshift({...base,id:'local-n-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),actor_name:actorName});LS.setItem('bhubondangaNotifications',JSON.stringify(a.slice(0,1200)))}catch(_){}if(recipientId===String(S.uid)){handleIncomingNotification(base)}const c=client();if(!c)return false;const variants=[base,{user_id:recipientId,actor_id:actor,type:base.type,title:base.title,message:base.message,url:base.url,post_id:base.post_id,created_at:now,read:false},{recipient_id:recipientId,actor_id:actor,type:base.type,title:base.title,created_at:now},{user_id:recipientId,actor_id:actor,type:base.type,title:base.title,created_at:now}];for(const raw of variants){const row={};for(const k in raw)if(raw[k]!==null&&raw[k]!==undefined)row[k]=raw[k];try{const r=await c.from('notifications').insert(row);if(!r.error)return true}catch(_){} }return false}
function subscribe(){const c=client();if(!c||!S.uid)return;for(const ch of S.channels)try{c.removeChannel(ch)}catch(_){}S.channels=[];try{const n=c.channel('bd-live-notifications-'+S.uid).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications'},p=>handleIncomingNotification(p.new)).subscribe();S.channels.push(n)}catch(_){}try{const m=c.channel('bd-live-messages-'+S.uid).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},p=>handleIncomingMessage(p.new)).subscribe();S.channels.push(m)}catch(_){} }
async function requestPermission(){try{if('Notification'in W&&Notification.permission==='default')await Notification.requestPermission()}catch(_){} }
async function boot(){css();injectBadges();S.session=await auth();S.uid=String(S.session?.user?.id||'');if(!S.uid){S.ready=true;return}S.notif=Number(get(`bd-signal-count-notification:${S.uid}`,0))||0;S.msg=Number(get(`bd-signal-count-message:${S.uid}`,0))||0;injectBadges();if(path()==='messages.html')await markMessagesRead();await refresh();subscribe();S.ready=true;W.dispatchEvent(new CustomEvent('bd:signals-ready'));clearInterval(S.timer);S.timer=setInterval(()=>{if(!D.hidden)refresh()},12000)}
D.addEventListener('pointerdown',prime,{once:true,capture:true});D.addEventListener('keydown',prime,{once:true,capture:true});
D.addEventListener('click',e=>{const a=e.target.closest('a[href*="notifications.html"],a[href*="messages.html"]');if(a){prime();requestPermission()}},true);
W.addEventListener('storage',e=>{if(['bhubondangaNotifications','bd-signal-seen-events'].includes(e.key)||String(e.key||'').startsWith('bd-signal-'))refresh()});
W.addEventListener('focus',()=>refresh());D.addEventListener('visibilitychange',()=>{if(!D.hidden)refresh()});
new MutationObserver(()=>injectBadges()).observe(D.documentElement,{childList:true,subtree:true});
W.BD_SIGNAL_CENTER={state:S,boot,refresh,injectBadges,getNotificationRows,markNotificationsRead,markMessagesRead,handleIncomingNotification,handleIncomingMessage,sendNotification,requestPermission,prime};
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();