/* ভুবনডাঙ্গা Supabase data bridge v1 */
(function(W){'use strict';
const local={read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch(e){return f}},write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return v}catch(e){return v}}};
const client=()=>W.BhubondangaAuth?.client||null;
async function user(){try{return (await W.BhubondangaAuth?.current?.())?.user||null}catch(e){return null}}
async function listPosts({category='',authorId='',limit=20,offset=0}={}){const c=client();if(!c)return local.read('bhubondangaPosts',[]).slice(offset,offset+limit);let q=c.from('posts').select('*').in('status',['published']).order('created_at',{ascending:false}).range(offset,offset+limit-1);if(category)q=q.eq('category',category);if(authorId)q=q.eq('author_id',authorId);const{data,error}=await q;if(error)throw error;return data||[];}
async function createPost(post){const u=await user();if(!u)throw new Error('লগইন প্রয়োজন');const safety=W.BhubondangaProfanity?.scan?.(`${post.title||''} ${post.body||''}`)||{flagged:false,matches:[]};const row={id:post.id||crypto.randomUUID(),author_id:u.id,author_username:post.author_username||u.user_metadata?.username||u.email?.split('@')[0],author_name:post.author_name||u.user_metadata?.full_name||u.email?.split('@')[0],author_avatar:post.author_avatar||u.user_metadata?.avatar_url||'',type:post.type||'poem',category:post.category||'কবিতা',title:post.title||'শিরোনামহীন',body:post.body||'',original_author:post.original_author||'',media_url:post.media_url||'',media_type:post.media_type||'',card_style:post.card_style||localStorage.getItem('bhubondangaGlassTheme')||'pearl',visibility:post.visibility||'public',status:safety.flagged?'pending_review':'published'};const c=client();if(c){const{data,error}=await c.from('posts').insert(row).select().single();if(error)throw error;if(safety.flagged)await W.BhubondangaProfanity?.queuePostForModeration?.(data||row,safety.matches,c);return data;}const all=local.read('bhubondangaPosts',[]);all.unshift(row);local.write('bhubondangaPosts',all);if(safety.flagged)await W.BhubondangaProfanity?.queuePostForModeration?.(row,safety.matches,null);return row;}
async function addComment({postId,body,parentId=null}){const u=await user();if(!u)throw new Error('লগইন প্রয়োজন');const safety=W.BhubondangaProfanity?.scan?.(body)||{flagged:false};if(safety.flagged)throw new Error(W.BhubondangaProfanity?.commentMessage||'আপত্তিকর শব্দ আছে—মন্তব্য পাঠানো হয়নি');const row={id:crypto.randomUUID(),post_id:postId,author_id:u.id,parent_id:parentId,author_username:u.user_metadata?.username||u.email?.split('@')[0],author_name:u.user_metadata?.full_name||u.email?.split('@')[0],body,status:'published'};const c=client();if(!c)return row;const{data,error}=await c.from('comments').insert(row).select().single();if(error)throw error;return data;}
async function notifications(limit=30){const u=await user(),c=client();if(!u||!c)return[];const{data,error}=await c.from('notifications').select('*').eq('user_id',u.id).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[];}
async function resolvePoetImage({slug='',name=''}){const c=client();if(c&&slug){const{data}=await c.from('poets').select('image_url').eq('slug',slug).maybeSingle();if(data?.image_url)return data.image_url;}if(!name)return'';try{const title=encodeURIComponent(name.replace(/\s+/g,'_'));const r=await fetch(`https://bn.wikipedia.org/api/rest_v1/page/summary/${title}`,{headers:{accept:'application/json'}});if(r.ok){const j=await r.json();return j.thumbnail?.source||j.originalimage?.source||'';}}catch(e){}return'';}
async function submitContribution(row){const u=await user();if(!u)throw new Error('লগইন প্রয়োজন');const payload={editor_id:u.id,original_author:row.original_author,work_title:row.work_title,source_url:row.source_url||'',contribution_type:row.contribution_type||'addition',status:'pending'};const c=client();if(!c){const all=local.read('bhubondangaEditorContributions',[]);all.unshift(payload);local.write('bhubondangaEditorContributions',all);return payload;}const{data,error}=await c.from('editor_contributions').insert(payload).select().single();if(error)throw error;return data;}
W.BhubondangaData=Object.freeze({listPosts,createPost,addComment,notifications,resolvePoetImage,submitContribution,user,client});
})(window);